img=imread('images/lena.bmp');
h=fspecial('motion',50,45);
img1=imfilter(img,h,'circular','conv');
img2=imnoise(img1,'gaussian',0,0.01);
figure(1);
imshow(img2);
title('lena运动模糊+高斯噪声');
% V=0.0001;
% NoisePower=V*numel(img);
% [g,LAGRA]=deconvreg(img1,h,NoisePower);
% figure(2);
% imshow(g);
% title('约束最小二乘滤波的结果');
