%主函数
img1=imread('images/test1.pgm','pgm');
img1=imread('images/test2.tif','tif');
img3=imread('images/test3_corrupt.pgm','pgm');
img4=imread('images/test4 copy','bmp');
%butterworth低通
alpha=BWLFilter(img1,10,2)
alpha=BWLFilter(img1,30,2)
alpha=BWLFilter(img1,50,2)
alpha=BWLFilter(img1,80,2)
%Gaussian低通
alpha=GLFilter(img1,10)
alpha=GLFilter(img1,30)
alpha=GLFilter(img1,50)
alpha=GLFilter(img1,80)
%butterworth高通
alpha=BWHFilter(img3,5,2)
alpha=BWHFilter(img3,10,2)
alpha=BWHFilter(img3,30,2)
%Gaussian高通
alpha=GHFilter(img3,5)
alpha=GHFilter(img3,10)
alpha=GHFilter(img3,30)
%拉普拉斯算子滤波
LapFilter(img3);
LapFilter(img3);
%Umask
Unmask(img3,10,1,1);
Unmask(img3,30,1,1);